# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'CWPBY' do
    
    pod 'PopupDialog', '~> 0.5'
    pod 'UIImageColors', '~>1.2.1'

end
